#!/usr/bin/env python3
"""Download the webfonts and generate css/fonts.css so the site self-hosts them.

    python3 website/tools/fetch-fonts.py

Why self-host rather than link to the Google Fonts CDN:
  * no third-party request on page load (faster first paint, no tracking)
  * the page renders correctly offline and from file://
  * the exact font binaries are versioned alongside the site

Both families are SIL Open Font License 1.1, which permits this.

Google serves each family as a single variable woff2 covering the whole
weight axis, so we emit ONE @font-face per (family, style, subset) with a
`font-weight` range rather than one per weight. Same rendering, one download.
"""

import os
import re
import urllib.request
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
FONT_DIR = os.path.join(SITE, "assets", "fonts")
CSS_OUT = os.path.join(SITE, "css", "fonts.css")

# A desktop-Chrome UA is what makes the API return woff2 rather than ttf.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Montserrat:wght@300;400;500;600"
    "&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,600"
    "&display=swap"
)

# The site only sets Latin copy; dropping the other subsets saves ~1.5 MB.
KEEP_SUBSETS = ("latin", "latin-ext")

HEADER = """/* ==========================================================================
   AYRA — self-hosted webfonts

   Generated by tools/fetch-fonts.py. Do not hand-edit; re-run the script.

   Montserrat and Source Serif 4 are both licensed under the SIL Open Font
   License 1.1 (see assets/fonts/OFL.txt), which permits self-hosting.
     Montserrat      https://fonts.google.com/specimen/Montserrat
     Source Serif 4  https://fonts.google.com/specimen/Source+Serif+4

   These stand in for the brand fonts (Publico Text Semibold / Gotham Book),
   which are commercially licensed. To swap the real fonts in, add their
   @font-face rules here and put them first in the --font-display and
   --font-body stacks in styles.css.
   ========================================================================== */

"""


def fetch(url, binary=False):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = response.read()
    return payload if binary else payload.decode("utf-8")


def slug(text):
    return re.sub(r"[^A-Za-z0-9]+", "", text)


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = fetch(CSS_URL)

    blocks = re.findall(
        r"/\*\s*([\w\-\[\]]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S
    )

    faces = OrderedDict()

    for subset, body in blocks:
        if subset not in KEEP_SUBSETS:
            continue

        url = re.search(r"url\((https://[^)]+\.woff2)\)", body)
        family = re.search(r"font-family:\s*'([^']+)'", body)
        weight = re.search(r"font-weight:\s*(\d+)", body)
        style = re.search(r"font-style:\s*(\w+)", body)
        urange = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (url and family and weight and style and urange):
            continue

        key = (family.group(1), style.group(1), subset, url.group(1))
        face = faces.setdefault(key, {
            "min": int(weight.group(1)),
            "max": int(weight.group(1)),
            "range": urange.group(1).strip(),
        })
        face["min"] = min(face["min"], int(weight.group(1)))
        face["max"] = max(face["max"], int(weight.group(1)))

    rules = []
    downloaded = {}

    for (family, style, subset, url), face in faces.items():
        filename = "{}-{}-{}.woff2".format(slug(family), style, subset)
        if url not in downloaded:
            with open(os.path.join(FONT_DIR, filename), "wb") as handle:
                handle.write(fetch(url, binary=True))
            downloaded[url] = filename
            print("  downloaded", filename)

        weight = (str(face["min"]) if face["min"] == face["max"]
                  else "{} {}".format(face["min"], face["max"]))

        rules.append(
            "/* {} — {} {} */\n"
            "@font-face {{\n"
            "  font-family: '{}';\n"
            "  font-style: {};\n"
            "  font-weight: {};\n"
            "  font-display: swap;\n"
            "  src: url('../assets/fonts/{}') format('woff2');\n"
            "  unicode-range: {};\n"
            "}}".format(
                family, style, weight,
                family, style, weight, downloaded[url], face["range"],
            )
        )

    with open(CSS_OUT, "w") as handle:
        handle.write(HEADER + "\n\n".join(rules) + "\n")

    print("wrote {} ({} faces, {} files)".format(
        os.path.relpath(CSS_OUT, SITE), len(rules), len(downloaded)))


if __name__ == "__main__":
    main()
